### ISSUE TITLE
optimized model in CNORfuzzy

### ISSUE THREAD

**Issue by abcd99hy** [saezlab/CellNOptR#11] opened 2019-06-08 03:22 UTC
Using demo data in CellNOptR, I optimized PKN model.
I obtained the same plot to Figure 2 (left) in "https://bioconductor.org/packages/release/bioc/vignettes/CNORfuzzy/inst/doc/CNORfuzzy-vignette.pdf".
However, after "writeFuzzyNetwork", the optimization model in ".dot" file doesn't include any edges to "Hsp27", even though "Hsp27" was stimulated by TGFα in prediction results.
Are there any mistakes in following codes?

#loading model
#ToyDataMMB.csv and ToyPKNMMB.sif are demo data in CellNOptR.
library(CNORfuzzy)
library(CellNOptR)
CNOlistToy_1<-CNOlist("ToyDataMMB.csv")
pknmodel_1<-readSIF("ToyPKNMMB.sif")
#parameter setting
paramsList_1<-defaultParametersFuzzy(CNOlistToy_1, pknmodel_1)
paramsList_1$popSize = 50
paramsList_1$maxGens = 50
paramsList_1$optimisation$maxtime = 30
paramsList_1$verbose = FALSE
#analysis
N = 1
allRes = list()
paramsList_1$verbose=TRUE
for (i in 1:N){
Res = CNORwrapFuzzy(CNOlistToy_1, pknmodel_1, paramsList=paramsList_1, verbose=TRUE)
allRes[[i]] = Res
}
summary_1= compileMultiRes(allRes,show=TRUE)
#plotting model
plotMeanFuzzyFit(0.1, summary_1$allFinalMSEs, allRes)
#write report
writeFuzzyNetwork(0.01, summary_1$allFinalMSEs, allRes, "output_CNOlistToy_1")
#plotting optimized model
library(DiagrammeR)
grViz("output_CNOlistToy_1_PKN.dot")

**Comment by gabora** [comment] 2019-06-11 07:26
Hi, 
thanks for the report, I can confirm this bug.
 will look at the details and get back to you soon.

**Comment by abcd99hy** [comment] 2019-06-12 13:30
Thanks. I will wait. Additionally, using CellNOptR and CNORfussy, sometimes I couldn't get same result even though I used same data. How should I handle this problem? Can I get stable simulation results changing some optimization parameters? Or, Should I do several optimization, and check the optimized model frequency?

**Comment by gabora** [comment] 2019-06-12 13:48
Hi, 
we wrote to the authors of the CNORFuzzy, M. Morris and T. Cokelaer. 
I was reading the vignette and in the caption of figure 7 you can read: 

> Note that the right panel wrongly labelled some edges in grey (e.g., no link out of IL1a; this is related to a current issue in the mapback step of the optimised model on the original one, which should be fixed in a future version)

This worries me a bit. 

Regarding reproducibility in CellNOpt
with the small toy model (presented in the vignette, through sections 3-9), it should be almost perfectly reproducible.

With the real case study (section 10), it is possible that the algorithm does not report the same solution as in the vignette because the solutions are not unique. The genetic algorithm uses random numbers and (unfortunately) the authors didn't provide the seed for the random number generator.

**Comment by abcd99hy** [comment] 2019-06-12 14:32
Hi,

Thank you for your answer.

About CNORFuzzy, I understood. I hope this will be fixed in the next version.

About reproducibility in CellNOptR, as you said, I could get same result using "ToyDataMMB.csv". However, I changed all values to "1" at 10 min, I sometimes got different results within 10 times simulations. 
In the article, "Comparing Signaling Networks between Normal and Transformed hepatocytes Using Discrete Logical Models", the authors said, "Model training was iterated 50 to 100 times for each set of data. Because of the stochastic nature of the genetic algorithm and the nonidentifiability of the models given data, different solutions were recovered each time. In common with most work on network inference, we addressed nonidentifiability by analyzing families of models instead of single solutions; in this work, models within 1% MSE (mean squared error)  of the best-fit model constituted the "consensus." " 
Does It mean that simulations was conducted in 50-100 times, and assumed the first model within 1% "MSE" as the best model? 
In vegnette on page 9, I could find "mse", but I think this is the mse at each nodes. Can I get total or model "MSE"  values?

**Comment by gabora** [comment] 2019-06-12 14:36
just to avoid confusion, when you write simulation, do you mean optimisation? 
Because simulation is deterministic in CellNOptR: it gives you always the same values (given that you don't change the network structure, i.e the bitString). But the optimisation of the network can result in different solutions.

**Comment by gabora** [comment] 2019-06-12 14:46
when you run the optimisation (gaBinaryT1), 
you can select the tolerance (`relTol`) which keeps the solutions that are among the top `relTol*100%`.  So to get the models within the 1% MSE of the best fit, set `relTol=0.01`. 

You will find the best performing model in the result list. 

bString | the best bitstring
bScore | the best score (MSE)
stringsTol | the bitstrings whose scores are within the tolerance (set by relTol)
stringsTolScores | the scores of the above-mentioned strings (here are the MSE of the top performing models)

**Comment by abcd99hy** [comment] 2019-06-12 15:19
Hi,

Thank you for your kind answer and sorry for bothering you.



I used "simulation" to mean "optimization".
I understood what you said.

I confirmed about optimization results.
Does "result list" mean reports?
In attached file,[report.pptx](https://github.com/saezlab/CellNOptR/files/3281995/report.pptx),
residual error: the best score(MSE)?
object function: the bestbitstring?

**Comment by gabora** [comment] 2019-06-12 16:03
results list: the output of gaBinaryT1 function.  please check the documentation:
in R studio type:
`?CellNOptR::gaBinaryT1()`

meanwhile, MK Morris answered, she cannot help fixing the bug. -- sorry. :(

@ptrairatphisan will invite you to the CNORProb package. It is similar to CNORFuzzy, but with a probabilistic interpretation. @ptrairatphisan is still in the group and will be happy to help you out in case you have questions. 

I will close this issue now because we deviated from the original question. 
But feel free to open a new if you have a question related to CellNOptR!

**Closed as completed by gabora** 2019-06-12 16:03 UTC
Labels: bug
